import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Footer } from '../components/footer';
import { Header } from '../components/header';

export default function Blog() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>

            <main className={styles.main}>
                <h1>Aquí estan todos los articulos del blog de JavaScript</h1>
            </main>

            <Footer />
        </div>
    );
}