import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { getAllFilesMetaData } from '../lib/mdx';
import Link from 'next/link';
import { Footer } from '../components/footer';

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>JavaScript Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href=":blank">JavaScript Blog!</a>
        </h1>

        <p className={styles.description}>
          Espacio para agregar contenido en{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href='/Blog' className={styles.card}>
            <a>
              <code className={styles.code}>Blog</code>
            </a>
          </Link>
        </div>

        <div className={styles.grid}>
          {posts.map( (posts) => (
            <Link key={posts.slug} href={`/${posts.slug}`}>
              <a className={styles.card}>
                <h2>{posts.title} &rarr;</h2>
                <p>{posts.date}.</p>
              </a>
            </Link>
          ))}
        </div>

      </main>
      
      <Footer/>
      
    </div>
  );
}

export async function getStaticProps() {

  const posts = await getAllFilesMetaData();
  console.log(posts);

  return {
    props: {posts},
  }
}
0