import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getAllFilesMetaData } from '../lib/mdx';
import Link from 'next/link';

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>JavaScript Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href=":blank">JavaScript Blog!</a>
        </h1>

        <p className={styles.description}>
          Espacio para agregar contenido en{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href='/Blog' className={styles.card}>
            <a>
              <code className={styles.code}>Blog</code>
            </a>
          </Link>
        </div>

        <div className={styles.grid}>
          {posts.map( (posts) => (
            <Link key={posts.slug} href={`/${posts.slug}`}>
              <a className={styles.card}>
                <h2>{posts.title} &rarr;</h2>
                <p>{posts.date}.</p>
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://www.uaemex.mx/" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/Logo_de_la_UAEMex.svg" alt="UAEMEX Logo" width={50} height={40} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {

  const posts = await getAllFilesMetaData();
  console.log(posts);

  return {
    props: {posts},
  }
}
